<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.12">
  <POU Name="FB_Btn" Id="{9d1b347e-0701-4dd1-a9e2-079105cb34be}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Btn
VAR_INPUT
	xStart:BOOL;
	xStop:BOOL;
	xReset:BOOL;
	xNextPas:BOOL;
	xAru:BOOL;
	
	xManualAct1GoIn: BOOL;
	xManualAct1GoOut : BOOL;
	
	xAirPressureOk : BOOL;
	
	xHomingPosReached : BOOL;
	
	//Btn used in Manual-Mode
	xSetHomePos : BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
]]></ST>
    </Implementation>
    <LineIds Name="FB_Btn">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>