<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="FB_Ia" Id="{066a8567-c425-448a-b812-c781f3454bc0}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Ia
VAR_INPUT
	fbConfig: FB_ConfigAnalog;  //Analog Input configuration
	IaEntree: LREAL;			//Analog input value on the Input-Pin
END_VAR
VAR_OUTPUT
	lrValeur: LREAL; 			//converted value in the user unit
	(*Not used ? *)lrEcart: LREAL; 		///écart de précision sur la valeur de consigne => valeur +/- écart
	(*Not used ? *)lrTension: LREAL;	///tension en volt
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//call the Method for converting
lrValeur:=fbConfig.mConvertAnToVal(IaEntree,lrTension=>lrTension,lrEcart=>lrEcart);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>