<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4020.6">
  <POU Name="FB_Qa" Id="{f0715c0c-30b0-4295-ae4b-91cb1e50682c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Qa
VAR_INPUT
	lrConsigne: LREAL;  		//user value to be converted in an analog value
	fbConfig: FB_ConfigAnalog; 	//Analog output configuration
END_VAR
VAR_OUTPUT
	QaSortie : DINT; 			//analog output
	lrEcart: LREAL; 			//actual error introduced while converting the value
	lrTension: LREAL; 			//Voltage on the Output-Pin depending on IrConsigne
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//call the Method for converting
QaSortie:=fbConfig.mConvertValToAn(lrConsigne,lrTension=>lrTension,lrEcart=>lrEcart);
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>